local function map(mode, lhs, rhs, opts)
  local options = {noremap = true, silent = true }
  if opts then options = vim.tbl_extend('force', options, opts) end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

map('n', '<leader>n', ':Neotree reveal toggle<cr>')
map('n', '<leader>y', '"+y')
map('n', '<leader>p', '"+p')
map('n', '<leader>w', ':w<cr>')
map('n', '<leader>q', ':q<cr>')
map('n', '<leader>/', ':nohlsearch<cr>')
map('n', '<C-h>', '<C-w>h')
map('n', '<C-j>', '<C-w>j')
map('n', '<C-k>', '<C-w>k')
map('n', '<C-l>', '<C-w>l')
map('n', '<C-p>', ':Telescope find_files<cr>')
map('n', '<M-g>', ':Telescope live_grep<cr>')
map('n', '<M-o>', ':Telescope oldfiles<cr>')
map('n', '<M-*>', ':Telescope grep_string<cr>')
map('n', '<M-b>', ':Telescope buffers<cr>')
map('n', '<M-r>', ':Telescope registers<cr>')
map('n', '<M-p>', ':Telescope projects<cr>')
map('n', '<M-q>', ':Telescope quickfix<cr>')
map('n', 'j', 'gj')
map('n', 'k', 'gk')
map('n', 'gj', 'j')
map('n', 'gk', 'k')
map('n', '<F5>', ":lua require'dap'.continue()<CR>")
map('n', '<F10>', ":lua require'dap'.step_over()<CR>")
map('n', '<F11>', ":lua require'dap'.step_into()<CR>")
map('n', '<F12>', ":lua require'dap'.step_out()<CR>")
map('n', '<leader>dr', ":lua require'dap'.repl_open()<CR>")
map('n', '<leader>dl', ":lua require'dap'.run_last()<CR>")
map('n', '<leader>b', ":lua require'dap'.toggle_breakpoint()<CR>")
map('n', '<leader>B', ":lua require'dap'.set_breakpoint(vim.fn.input('Breakpoint condition: '))<CR>")
map('n', '<leader>lp', ":lua require'dap'.set_breakpoint(nil, nil, vim.fn.input('Log point message: '))<CR>")
map('i', 'jj', '<Esc>')
map('i', 'jk', '<Esc>')

