local function map(mode, lhs, rhs, opts)
  local options = {noremap = true, silent = true }
  if opts then options = vim.tbl_extend('force', options, opts) end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

map('n', '<leader>n', ':Neotree reveal toggle<cr>')
map('n', '<leader>y', '"+y')
map('n', '<leader>p', '"+p')
map('n', '<leader>w', ':w<cr>')
map('n', '<leader>q', ':q<cr>')
map('n', '<leader>/', ':nohlsearch<cr>')
map('n', '<C-h>', '<C-w>h')
map('n', '<C-j>', '<C-w>j')
map('n', '<C-k>', '<C-w>k')
map('n', '<C-l>', '<C-w>l')
map('n', '<C-p>', ':Telescope find_files<cr>')
map('n', '<M-g>', ':Telescope live_grep<cr>')
map('n', '<M-o>', ':Telescope oldfiles<cr>')
map('n', '<M-*>', ':Telescope grep_string<cr>')
map('n', '<M-b>', ':Telescope buffers<cr>')
map('n', '<M-r>', ':Telescope registers<cr>')
map('n', '<M-p>', ':Telescope projects<cr>')
map('n', '<M-q>', ':Telescope quickfix<cr>')
map('n', 'j', 'gj')
map('n', 'k', 'gk')
map('n', 'gj', 'j')
map('n', 'gk', 'k')
map('i', 'jj', '<Esc>')
map('i', 'jk', '<Esc>')
